sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: xxxxxxxx
    access-key-secret: xxxxxxxxxxx
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: java-learn
  redis:
    host: localhost
    port: 6379
    database: 0
    password: ''
  wechat:
    appid: xxxxx
    secret: xxxxx
    mchid: xxxxxxx
    mchSerialNo: xxxxxxx
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: xxxxxxxxxxxxxxxx
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess
  shop:
    address: xxxxx
  baidu:
    ak: xxxxx
